# Generated by Django 3.0.4 on 2020-04-07 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(related_name='_book_tags_+', to='books.Book'),
        ),
    ]
